const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors({origin: '*'}));
app.use(express.json());
const APIKEY = "TEST";
const SITE_ID = "TEST";
let CA = 0;
app.get('/init-pay', (req,res)=>{ res.json({apikey: APIKEY, site_id: SITE_ID}); });
app.post('/verify-payment', (req,res)=>{ CA+=5000; res.json({ok:true}); });
app.post('/check-patron', (req,res)=>{ if(req.body.code==="7777") res.json({ok:true}); else res.json({ok:false}); });
app.get('/mon-ca', (req,res)=>{ if(req.query.code==="7777") res.json({ca:CA}); else res.json({error:"code faux"}); });
app.get('/', (req,res)=>{ res.send("BACKEND OK"); });
app.listen(10000, ()=>console.log("BACKEND MARCHE SUR PORT 10000"));
